import HomeHero from "./(public)/components/ui/homeHero";
import Stats from "./(public)/components/ui/Stats";
import TrustedBy from "./(public)/components/ui/TrustedBy";

export const metadata = {
  title: "Techtwen",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="bg-background text-foreground dark:bg-background dark:text-foreground  ">
      
      <div className="flex flex-col justify-between gap-20 mb-20">
        <HomeHero></HomeHero>

        <TrustedBy></TrustedBy>

        <Stats></Stats>
      </div>
      
    </div>
  );
}
